spring.application.name=api-gateway



server.port=8085








# Bloque para la funcionalidad de Donaciones
spring.cloud.gateway.server.webmvc.routes[0].id=donacion-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:3000
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/donacion/**

# Bloque para la funcionalidad de Registro
spring.cloud.gateway.server.webmvc.routes[1].id=register-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:3000
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/register/**