spring.application.name=api-gateway

server.port=8085

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8090/eureka}

# Bloque para la funcionalidad de Donaciones
spring.cloud.gateway.server.webmvc.routes[0].id=donacion-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${BFF_URI:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/donacion/**

# Bloque para la funcionalidad de Registro
spring.cloud.gateway.server.webmvc.routes[1].id=register-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${BFF_URI:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/usuario/**

# Bloque para la funcionalidad de Necesidad
spring.cloud.gateway.server.webmvc.routes[2].id=necesidad-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${BFF_URI:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/necesidad/**

# Bloque para la funcionalidad de Logística
spring.cloud.gateway.server.webmvc.routes[3].id=logistica-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${BFF_URI:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/logistica/**

# Bloque para la funcionalidad de Notificaciones
spring.cloud.gateway.server.webmvc.routes[4].id=notificacion-service
spring.cloud.gateway.server.webmvc.routes[4].uri=${BFF_URI:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/notificacion/**

# Bloque para la funcionalidad de Chat de voluntarios
spring.cloud.gateway.server.webmvc.routes[5].id=chat-service
spring.cloud.gateway.server.webmvc.routes[5].uri=${BFF_URI:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/chat/**
